[project]
name = "fantasy-game-mcp"
version = "0.1.0"
description = "Simple MCP server based on classic fantasy game actions and references."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.25.0",
    "requests>=2.32.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# If fantasygame is a subdirectory package, ensure it's discoverable:
[tool.hatch.build.targets.wheel]
packages = ["fantasygame"]
